#!/bin/python

# - Podmienka 1: nonspace_count == 819 (všetky znaky)
# - Podmienka 2: Všetky pixely musia mať farbu ASU maroon: RGB(0x8C, 0x1D, 0x40)

with open("example.cimg", "wb") as file:
    file.write(b"cIMG") 
    file.write((2).to_bytes(1, "little"))
    
    file.write((39).to_bytes(1, "little")) 
    file.write((21).to_bytes(4, "little")) 
    
    # Každý pixel: R (0x8C), G (0x1D), B (0x40), ASCII ('X')
    asu_maroon_r = 0x8C
    asu_maroon_g = 0x1D
    asu_maroon_b = 0x40
    
    for _ in range(39 * 21):
        file.write(bytes([asu_maroon_r, asu_maroon_g, asu_maroon_b, ord('X')]))
